import { describe, expect, it } from "vitest";
import { extractPublishedUrlFromComments } from "../src/lib/github";

describe("extractPublishedUrlFromComments", () => {
  it("最後のコメントに貼られたURLをそのまま返す", () => {
    const bodies = ["よろしくお願いします", "https://note.com/yurumeru_romance/n/n406bca7b2ccb"];
    expect(extractPublishedUrlFromComments(bodies)).toBe(
      "https://note.com/yurumeru_romance/n/n406bca7b2ccb"
    );
  });

  it("Claude Codeのattributionフッターしかない場合は無視し、より古いコメントの正しいURLを返す", () => {
    // 実際に発生した事故の再現: 記事issueに公開先URLだけの短いコメントがあった後、
    // Claude Codeが記事全文をコメントしてattributionフッター(claude.aiへのリンク)が
    // 「最後のコメント」になってしまったケース。
    const bodies = [
      "https://note.com/yurumeru_romance/n/n406bca7b2ccb",
      "## 記事全文\n\n(長い本文...)\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_",
    ];
    expect(extractPublishedUrlFromComments(bodies)).toBe(
      "https://note.com/yurumeru_romance/n/n406bca7b2ccb"
    );
  });

  it("URL直後のMarkdown記号(閉じ括弧・強調の`_`)を取り除く", () => {
    const bodies = ["続きはこちら→[記事はこちら](https://note.com/foo/bar)_"];
    expect(extractPublishedUrlFromComments(bodies)).toBe("https://note.com/foo/bar");
  });

  it("有効なURLがどのコメントにも無ければnullを返す", () => {
    const bodies = ["よろしくお願いします", "ありがとうございました"];
    expect(extractPublishedUrlFromComments(bodies)).toBeNull();
  });

  it("claude.ai以外の除外対象ホスト(claude.com/anthropic.com)も無視する", () => {
    const bodies = [
      "https://note.com/yurumeru_romance/n/nreal",
      "詳しくはこちら https://claude.com/claude-code をご覧ください",
    ];
    expect(extractPublishedUrlFromComments(bodies)).toBe("https://note.com/yurumeru_romance/n/nreal");
  });

  it("コメントが空配列の場合はnullを返す", () => {
    expect(extractPublishedUrlFromComments([])).toBeNull();
  });
});
