import { describe, expect, it } from "vitest";
import { extractPublishedUrlFromComments } from "../src/lib/github";
import { buildPublishedArticleUrlMatcher } from "../src/xPoster/articlePublication";
import { loadXPosterConfig } from "../src/xPoster/config";

const isAllowed = buildPublishedArticleUrlMatcher(loadXPosterConfig().publishedArticleUrlPattern);
const NOTE_URL = "https://note.com/yurumeru_romance/n/n406bca7b2ccb";

describe("extractPublishedUrlFromComments", () => {
  it("最後のコメントに貼られた記事URLをそのまま返す", () => {
    expect(extractPublishedUrlFromComments(["よろしくお願いします", NOTE_URL], isAllowed)).toBe(NOTE_URL);
  });

  it("Claude Codeのattributionフッターしかない場合は無視し、より古いコメントの記事URLを返す", () => {
    // 実際に発生した事故の再現: 記事issueに公開先URLだけの短いコメントがあった後、
    // Claude Codeが記事全文をコメントしてattributionフッター(claude.aiへのリンク)が
    // 「最後のコメント」になってしまったケース。
    const bodies = [NOTE_URL, "## 記事全文\n\n(長い本文...)\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"];
    expect(extractPublishedUrlFromComments(bodies, isAllowed)).toBe(NOTE_URL);
  });

  it("許可された形以外のURLは、除外リストに無いドメインでも使わない", () => {
    const bodies = [
      "参考: https://example.com/some-article",
      "別の人のnote https://note.com/someone_else/n/nabc123",
      "マガジン https://note.com/yurumeru_romance/m/mabc123",
    ];
    expect(extractPublishedUrlFromComments(bodies, isAllowed)).toBeNull();
  });

  it("同じコメントに複数のURLがある場合、許可された形のものを拾う", () => {
    const bodies = [`下書き https://docs.example.com/draft 公開先 ${NOTE_URL}`];
    expect(extractPublishedUrlFromComments(bodies, isAllowed)).toBe(NOTE_URL);
  });

  it("URL直後のMarkdown記号(閉じ括弧・強調の`_`)を取り除いてから判定する", () => {
    expect(extractPublishedUrlFromComments([`続きはこちら→[記事](${NOTE_URL})_`], isAllowed)).toBe(NOTE_URL);
  });

  it("記事URLの後ろに余計なパスやクエリが付いたものは使わない", () => {
    expect(extractPublishedUrlFromComments([`${NOTE_URL}?ref=x`], isAllowed)).toBeNull();
  });

  it("有効なURLがどのコメントにも無い、またはコメントが無ければnullを返す", () => {
    expect(extractPublishedUrlFromComments(["よろしくお願いします"], isAllowed)).toBeNull();
    expect(extractPublishedUrlFromComments([], isAllowed)).toBeNull();
  });
});
